### ISSUE TITLE
Travis + Saucelabs: protractor Unexpected server error

### ISSUE THREAD

**Issue by AdamQuadmon** [teerapap/grunt-protractor-runner#34]
```
Running "protractor" task
Using SauceLabs selenium server at http://adamquadmon:xxxx@ondemand.saucelabs.com:80/wd/hub

/home/travis/build/xxx/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:1542
      throw error;
            ^
UnknownError: Unexpected server error.
```

my .travis.yml:

```
language: node_js
node_js:
  - "0.10"
before_script:
  - gem install compass
  - npm install -g bower
  - npm install -g protractor
  - npm install grunt-cli
  - npm install
  - bower install
script:
  #- grunt test:mocha:saucelabs
  - grunt test:jasmine:saucelabs # this is grunt-protractor-runner
addons:
  sauce_connect:
    username: "adamquadmon"
    access_key: "xxx"
  hosts:
    - xxx.com
```
- I tried both with local or -g protractor installations
- I can run saucelabs test from my local
- I can run saucelabs test with grunt-mocha-protractor with the same configuration

that's why I think the issue is related to this task.
